version: '3.8'
services:
  mongo:
    image: mongo:4.4
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
  redis:
    image: redis:6.2
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bse-stock
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    environment:
      MONGODB_URI: mongodb://mongo:27017/bse_data
      REDIS_URI: redis://redis:6379
